<a href="https://colab.research.google.com/github/asha-92ddsmlp/Google-Colab-for-Data-Science-AI-using-Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array(50)
arr1 = np.array([1])
arr2 = np.array([[1]])
arr3 = np.array([[[1]]])
arr4 = np.array([[[[1]]]])

print(arr)



print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

50
0
1
2
3
4


In [3]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [9, 8, 2]]])
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)
print(d)
print(d.ndim)


42
0
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [9 8 2]]]
3


In [4]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


In [5]:
arr = np.array([12, 20, 33, 44])

print(arr[0])


12


In [6]:
arr = np.array([1, 2, 3, 4])

print(arr[0] + arr[3])

5


In [7]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 2])

2nd element on 1st row:  3


In [8]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [5,1,2,0,7]])

print('2nd element on 1st row: ', arr[0:3, 0])

2nd element on 1st row:  [1 6 5]


In [9]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0:2, 2:5])

2nd element on 1st row:  [[ 3  4  5]
 [ 8  9 10]]


In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6],[6,8,7]], [[7, 8, 9], [10, 11, 12],[6,8,7]]])
print(arr)
print("-"*20)
print(arr[1, 0:2, 0:3])

[[[ 1  2  3]
  [ 4  5  6]
  [ 6  8  7]]

 [[ 7  8  9]
  [10 11 12]
  [ 6  8  7]]]
--------------------
[[ 7  8  9]
 [10 11 12]]


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim: ', arr[-2, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  5


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6:2])

[2 4 6]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [19]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [21]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
arr[2] = 40

print(arr)
print(x)

[42  2 40  4  5]
[1 2 3 4 5]


In [22]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
arr[2] = 40

print(arr)
print(x)

[42  2 40  4  5]
[42  2 40  4  5]


In [23]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [25]:
arr = np.array([1, 2, 3, 4], ndmin=2)

print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]]
shape of array : (1, 4)


In [26]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(-1, 4)

print(newarr)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3, 2)
print(newarr)
n=newarr.reshape(-1)
print(n)
# n=arr.reshape(3,-1)
# print(n.base)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  # print(x)
  for y in x:
    print(y)


1
2
3
4
5
6


In [32]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
for x in arr:
  # [[1, 2, 3], [4, 5, 6]]
  for y in x:
    #[1, 2, 3]
    for z in y:
      print(z)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [33]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [34]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [36]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [38]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [39]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[50, 60], [75, 82]])
print(arr1)
print(arr2)
print(arr3)
arr = np.concatenate((arr1, arr2, arr3), axis=1)

print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[50 60]
 [75 82]]
[[ 1  2  5  6 50 60]
 [ 3  4  7  8 75 82]]


In [40]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2,arr3), axis=1)

print(arr)

[[1 4 4]
 [2 5 5]
 [3 6 6]]


In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([4, 2, 6])

arr = np.stack((arr1, arr2,arr3))

print(arr)

[[1 2 3]
 [4 5 6]
 [4 2 6]]


In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([4, 2, 6])

arr = np.hstack((arr1, arr2,arr3))

print(arr)

[1 2 3 4 5 6 4 2 6]


In [43]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)
for i in newarr:
  print(i)

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [46]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)
newarr = np.array_split(arr, 3, axis=1)[2]

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [50]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [51]:
arr = np.array([6, 7, 8, 9,10])

x = np.searchsorted(arr, 10)

print(x)

4


In [52]:
arr = np.array([5, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [53]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6,8])

print(x)

[1 2 3 4]


In [54]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [55]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [56]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [57]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [58]:
#using True to False
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[np.logical_not(x)]

print(newarr)

[42 44]


In [59]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [61]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr%2==1

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[ True False  True False]
[41 43]


In [62]:
from numpy import random

x = random.rand()

print(x)

0.8187185826367159


In [63]:
from numpy import random

x = random.rand(10)

print(x)

[0.47227733 0.27667778 0.11957091 0.24109822 0.11517767 0.9403222
 0.04945868 0.3811109  0.98862786 0.63650596]


In [64]:
from numpy import random

x = random.randint(50,100)

print(x)

82


In [65]:
x = random.randint(50, size=(20))

print(x)

[41 23 19 41 18 32  3 27 26 38 18 42 39 14  0 22  4 39  8 16]


In [66]:
x = random.randint(50,70, size=(10))

print(x)

[63 52 60 60 68 51 58 66 67 64]


In [67]:
x = random.randint(50,70, size=(3,5))

print(x)
print(x.sum())

[[69 53 65 51 64]
 [66 69 58 60 60]
 [55 64 57 57 69]]
917


In [68]:
x = random.randint(50,70, size=(3,5))

print(x)
print(x.mean())

[[51 68 64 66 67]
 [60 51 50 64 55]
 [50 65 63 59 62]]
59.666666666666664


In [69]:
x = random.choice([3, 5, 7, 9], size=(5))

print(x)

[7 7 5 9 5]


In [70]:
x = random.choice([3, 5, 7, 9], size=(5,3))

print(x)

[[5 9 3]
 [7 9 3]
 [9 5 3]
 [7 3 5]
 [3 9 3]]


In [71]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.5, 0.1], size=(10))

print(x)

[7 7 9 7 3 3 3 7 9 5]


In [72]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,3))

print(x)

[[3 5 7]
 [7 7 7]
 [7 7 5]]


In [73]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)

print(arr)

[3 5 4 2 1]


In [74]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))
print(arr)

[5 2 1 4 3]
[1 2 3 4 5]


In [75]:
x = random.normal(size=(2, 3))

print(x)

[[-0.37025409  1.8530765   0.24239147]
 [-1.58169634 -0.42478391  0.51452381]]


In [76]:
x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[ 1.39635687 -2.08273227  1.31222908]
 [ 0.38625248  3.24377313  0.61067857]]


In [77]:
x = random.binomial(n=50, p=0.1, size=10)

print(x)

[6 6 4 4 7 4 2 6 1 4]


In [78]:
x = random.poisson(lam=5, size=10)

print(x)

[6 4 7 6 2 4 6 3 6 5]
